[package]
name = "tictactoe-engine"
version = "0.1.0"
authors = ["birchmd"]

[lib]
name = "player"
crate-type = ["cdylib"]

[dependencies]
wasmi = "0.4.2"
parity-wasm = "0.35.1"

[profile.release]
panic = "abort"
lto = true
opt-level = "z"